services:
  db:
    container_name: 'mastodon-db'
    image: postgres:14-alpine
    restart: unless-stopped
    shm_size: 256mb
    networks:
      - default
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    command: postgres -c 'max_connections=100'

  redis:
    container_name: 'mastodon-redis'
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  console:
    container_name: 'mastodon-console'
    image: ghcr.io/mastodon/mastodon:v4.3.2 # Replace with other when needed
    restart: 'no'
    env_file: .env.production
    command: /bin/bash
    depends_on:
      - redis
    networks:
      - default
      - proxy
    volumes:
      - ./system:/mastodon/public/system
      #- /data/mastodon/public/system:/mastodon/public/system # Uncomment if you have a data directory - comment the local line if that's the case

  web:
    container_name: 'mastodon-web'
    image: ghcr.io/mastodon/mastodon:v4.3.2 # Replace with other when needed
    restart: unless-stopped
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    environment:
      - WEB_CONCURRENCY=1
      - MAX_THREADS=5
    networks:
      - default
      - proxy
    ports:
      - '3000:3000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1",
        ]
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./system:/mastodon/public/system
      #- /data/mastodon/public/system:/mastodon/public/system # Uncomment if you have a data directory - comment the local line if that's the case
      - ./system:/mastodon/public/robots.txt:ro
      #- /data/mastodon/public/robots.txt:/mastodon/public/robots.txt:ro # Uncomment if you have a data directory - comment the local line if that's the case

  streaming:
    container_name: 'mastodon-streaming'
    image: ghcr.io/mastodon/mastodon-streaming:v4.3.2 # Replace with other tag when needed
    restart: unless-stopped
    env_file: .env.production
    environment:
      - DB_POOL=20
    command: node ./streaming/index.js
    networks:
      - proxy
      - default
    ports:
      - '4000:4000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1",
        ]
    depends_on:
      - db
      - redis

  sidekiq:
    container_name: 'mastodon-sidekiq'
    image: ghcr.io/mastodon/mastodon:v4.3.2
    restart: unless-stopped
    env_file: .env.production
    environment:
      - DB_POOL=25
    command: bundle exec sidekiq -c 25
    depends_on:
      - db
      - redis
    networks:
      - proxy
      - default
    volumes:
      - ./system:/mastodon/public/system
      # - /data/mastodon/system:/mastodon/public/system # Uncomment if you have a data directory - comment the local line if that's the case
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    ports:
      - '127.0.0.1:9200:9200'

  es:
    container_name: 'mastodon-es'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    restart: unless-stopped
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true'
      - 'xpack.license.self_generated.type=basic'
      - 'xpack.security.enabled=false'
      - 'xpack.watcher.enabled=false'
      - 'xpack.graph.enabled=false'
      - 'xpack.ml.enabled=false'
      - 'bootstrap.memory_lock=true'
      - 'cluster.name=mastodon-es'
      - 'discovery.type=single-node'
      - 'thread_pool.write.queue_size=1000'
    networks:
      - proxy
      - default
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail localhost:9200/_cluster/health || exit 1',
        ]
    volumes:
      - ./esearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  proxy:
  default:
    internal: true
